index.repository.path=G:\\product\\data\\central-index
versionStoreFile=${index.repository.path}\\version.txt
index.repository.shortIndexFile=${index.repository.path}\\short.index
doc.root=G:\\product\\artifact-doc\\
spring.devtools.restart.exclude=static/**,public/**
spring.web.resources.static-locations=classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:${doc.root}